apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: ksrebuildsimple
data:
  port: '80'
  host: '0.0.0.0'
  pgdatabase: 'postgres'
  pgport: '5432'
  hosturl: 'http://20.124.43.17'
  oktaurl: 'https://dev-96311573.okta.com'
  pg_password: "dAGNs84V3TM2"